### ISSUE TITLE
stop() doesn't stop

### ISSUE THREAD

**Issue by gruppler** [samizdatco/arbor#21]
If I stop the particle system while it's running, the system doesn't stop completely. The nodes seem to stop moving relative to their connected nodes, but the entire system continues to gravitate toward the center.

**Comment by gruppler** [comment]
It appears that the webworker continues to run for awhile after stopping. Is there a way to kill it, or can you add an option to not use webworkers?

**Comment by veu** [comment]
I have the same problem. After calling ParticleSystem.stop(), the method ParticleSystem._updateBound still gets called. Additionally, when adding edges to the graph, the simulation restarts. Both of these don't happen when web workers are disabled.

**Comment by kjyv** [comment]
I have a similar problem, the other way round (not using webworkers so far):
I can stop and it stops immediately but I can't start again. Calling start(), the animation is still stopped.
I can still add edges though, but they don't show.

**Comment by kjyv** [comment]
Debugging the non-minified version, I can see that calling start calls system.js:start which in turn calls state.kernel.start, however not passing any parameters that start needs (unpause) to actually continue running. I can fix my issue by changing system.js:75-77 to   

``` javascript
start:function(unpause){
        state.kernel.start(unpause)
},
```

Actually, I'll add this as a new issue and provide a fork with the fix.
