### ISSUE TITLE
Unexpected token in attribute selector: '!'.

### ISSUE THREAD

**Issue by muratkesin** [samizdatco/arbor#5]
using web workers
physics: [xpconnect wrapped (nsISupports, nsIDOMEvent, nsIWorkerErrorEvent)] { type="error", target=Worker, more...}

Failed to load script: /arbor.js (nsresult = 0x805303f4)

**Comment by AlexandreAbreu** [comment]
This is a requirement of the webworkers that you cannot load a webworker associated javascript from the localfilesystem or from a domain that is not the domain of origin of the rest of the site.

I added to my forked repo a little python webserver that serves that purpose:

https://github.com/AlexandreAbreu/arbor

just run it and access the website with "http://localhost:8000/demos/echolalia/" for example.

**Comment by AlexandreAbreu** [comment]
I can issue a pull request if the server is useful.

**Comment by muratkesin** [comment]
thanks for your answer.
